In [3]:
import numpy as np
from itertools import combinations_with_replacement, product

In [5]:
x=rndMatWithRank(1000, 3, 3, 0.)

In [7]:
x.shape

(1000, 3)

In [8]:
cov_=np.cov(x, rowvar=False)

In [9]:
cov_

array([[ 0.96384036, -0.05270535,  0.04284205],
       [-0.05270535,  0.90631614,  0.05027304],
       [ 0.04284205,  0.05027304,  1.02322969]])

In [13]:
np.random.uniform(size=cov_.shape[0]) * np.diag(cov_) **.5

array([0.3611091 , 0.61467763, 0.02664808])

In [12]:
np.diag(cov_)

array([0.96384036, 0.90631614, 1.02322969])

In [4]:
def rndMatWithRank(nSamples,nCols,rank,sigma=0,homNoise=True): 
    rng=np.random.RandomState()
    U,_,_=np.linalg.svd(rng.randn(nCols,nCols)) 
    x=np.dot(rng.randn(nSamples,rank),U[:,:rank].T) 
    if homNoise: 
        x+=sigma*rng.randn(nSamples,nCols)
    else: 
        sigmas=sigma*(rng.rand(nCols)+.5) 
        x+=rng.randn(nSamples,nCols)*sigmas 
    return x

In [2]:
np.random.randn(3, 4)

array([[ 0.82773958,  0.24117104,  0.29006296, -0.4596736 ],
       [-0.22942182,  0.48161133,  0.39792422, -2.35322449],
       [ 1.9860489 , -1.70572266,  1.43580598, -0.17767386]])

In [9]:
def pigeonHole(k, n):
    for j in combinations_with_replacement(range(n), k):
        r=[0]*n
        for i in j:
            r[i]+=1
        yield r

In [12]:
def pigeonHoleList(k, n):
    res = []
    for j in combinations_with_replacement(range(n), k):
        r=[0]*n
        for i in j:
            r[i]+=1
        res.append(r)
    return res

In [13]:
parts, w=pigeonHoleList(6, 3), None

In [15]:
part_=parts[5]

In [24]:
w_=np.array(part_) / float(6)

In [25]:
sign = []
for prod_ in product([-1, 1], repeat=3):
    sign.append(prod_)

In [28]:
prod_=sign[2]

In [29]:
w_

array([0.66666667, 0.        , 0.33333333])

In [30]:
prod_

(-1, 1, -1)

In [32]:
(w_*prod_).reshape(-1, 1)

array([[-0.66666667],
       [ 0.        ],
       [-0.33333333]])

In [9]:
parts, numThreads_, numAtoms = [0], 6, 20

In [10]:
for num in range(numThreads_):
    part = 1 + 4 * (parts[-1] ** 2 + parts[-1] + numAtoms * (numAtoms + 1.) / numThreads_)
    part = (-1 + part ** 0.5) / 2.
    parts.append(part)

In [13]:
parts

array([ 0,  8, 11, 14, 16, 18, 20])

In [12]:
parts = np.round(parts).astype(int)

In [14]:
np.diff(parts)[::-1]

array([8, 3, 3, 2, 2, 2])

In [16]:
np.cumsum(np.diff(parts)[::-1])

array([ 2,  4,  6,  9, 12, 20], dtype=int32)

In [2]:
r=np.random.normal(0, 0.01, size=(1000, 10000))

In [4]:
np.log((1+r).cumprod(axis=0))

array([[ 0.00103059, -0.00091815, -0.0039172 , ..., -0.0051284 ,
        -0.01456192,  0.00550041],
       [-0.00390738, -0.00335373, -0.00354153, ..., -0.00341111,
        -0.00309146,  0.00538962],
       [ 0.00716768, -0.00066802, -0.01452469, ...,  0.00187567,
         0.00877441,  0.01157346],
       ...,
       [-0.04646563, -0.39426069, -0.04233772, ...,  0.04860675,
        -0.33264894, -0.5478318 ],
       [-0.05943003, -0.38908043, -0.04302327, ...,  0.04780893,
        -0.33856471, -0.54580694],
       [-0.04914948, -0.39509339, -0.05050572, ...,  0.05814427,
        -0.33082036, -0.53753151]])

In [6]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])